config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  # get '/users/:id', to: 'users#show'
  # /users/3 -> Users controller, show action, params {id: '3'}
  resources :users, only: [:index, :show]

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  validates :image, presence: true

  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :comments, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def is_belongs_to? user
    Post.find_by(user_id: user.id, id: id)
  end

  def is_liked user
    Like.find_by(user_id: user.id, post_id: id)
  end

  def is_bookmarked user
    Bookmark.find_by(user_id: user.id, post_id: id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[twitter]

  validates :name, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image.gsub!("_normal", "") # assuming the user model has an image
      user.uid = auth.uid
      user.provider = auth.provider
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%")
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :website, :bio])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)
    if @bookmark.save
      @post = @bookmark.post
      @is_bookmarked = @bookmark
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @post = @bookmark.post
    if @bookmark.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def bookmark_params
    params.permit :user_id, :post_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @comments = @post.comments.includes(:user)
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      @post = @comment.post
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    if @comment.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def comment_params
    params.required(:comment).permit :user_id, :post_id, :content
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(like_params)
    @post = @like.post
    if @like.save
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @post = @like.post
    if @like.destroy
      respond_to :js
    else
      flash[:alert] = "Something went wrong ..."
    end
  end

  private
  def like_params
    params.permit :post_id
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:show, :destroy]

  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5).includes(:photos, :user, :likes).
      order("created_at desc")
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      if params[:images]
        params[:images].each do |img|
          @post.photos.create(image: params[:images][img])
        end
      end

      redirect_to posts_path
      flash[:notice] = "Saved ..."
    else
      flash[:alert] = "Something went wrong ..."
      redirect_to posts_path
    end
  end

  def show
    @photos = @post.photos
    @likes = @post.likes.includes(:user)
    @comment = Comment.new
    @is_liked = @post.is_liked(current_user)
    @is_bookmarked = @post.is_bookmarked(current_user)
  end

  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = "Post deleted!"
      else
        flash[:alert] = "Something went wrong ..."
      end
    else
      flash[:notice] = "You don't have permission to do that!"
    end
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find_by id: params[:id]

    return if @post
    flash[:danger] = "Post not exist!"
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit :content
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.search(params[:term])
    respond_to :js
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:photos, :likes, :comments)
    @saved = Post.joins(:bookmarks).where(user_id: current_user.id).
      includes(:photos, :likes, :comments) if @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url user
    return user.image if user.image
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/create.js.erb
$('#bookmark-icon-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>');
console.log("create bookmark success");

app/views/bookmarks/destroy.js.erb
$('#bookmark-icon-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>');
console.log("delete bookmark success");

app/views/comments/create.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", {post: @post} %>');
$('#comment-form-post-<%= @post.id.to_s %> #comment_content').val("");
console.log("create comment success");

app/views/comments/destroy.js.erb
$('#comment-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/comment_list", {post: @post} %>');
console.log("delete comment success");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' if current_user %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>

    <% if flash.any? %>
      <script type="text/javascript">
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          toastr.<%= type %>('<%= value %>')
        <% end %>
      </script>
    <% end %>
  </body>
</html>

app/views/likes/create.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "Love", like_path(@like), method: :delete, remote: true, class: "core-sprite loved hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", {likes: @post.likes} %>');
console.log("create like success");

app/views/likes/destroy.js.erb
$('#like-icon-post-<%= @post.id.to_s %>').
  html('<%= link_to "Loved", post_likes_path(@post), method: :post, remote: true, class: "core-sprite love hide-text" %>');
$('#like-text-post-<%= @post.id.to_s %>').
  html('<%= j render "posts/like_text", {likes: @post.likes} %>');
console.log("delete like success");

app/views/pages/home.html.erb
<%= link_to "Log out", destroy_user_session_path, method: :delete %>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_bookmark_icon.html.erb
<% if is_bookmarked.present? %>
  <%= link_to "Bookmarked", bookmark_path(is_bookmarked), method: :delete, remote: true,
    class: "core-sprite bookmarked hide-text" %>
<% else %>
  <%= link_to "Bookmark", post_bookmarks_path(post), method: :post,
    remote: true, class: "core-sprite bookmark hide-text" %>
<% end %>

app/views/posts/_comment_form.html.erb
<%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= f.text_field :content, class: "form-control comment-input border-0",
     placeholder: "Add a comment ...", autocomplete: :off %>
<% end %>

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "Delete comment", comment_path(comment),
        method: :delete, remote: true, class: "core-sprite delete-comment hide-text" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user),
          class: "no-text-decoration normal-color" %>
      </strong>
    </span>
    <span><%= comment.content %></span>
  </div>
<% end %>

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Love", like_path(is_liked), method: :delete, remote: true,
    class: "core-sprite loved hide-text" %>
<% else %>
  <%= link_to "Loved", post_likes_path(post), method: :post, remote: true,
    class: "core-sprite love hide-text" %>
<% end %>

app/views/posts/_like_text.html.erb
<% likes.each.with_index do |like, index| %>
<strong>
  <% if likes.size == 1 %>
    <%= like.user.name %> </strong> likes this
  <% elsif like == likes.last %>
    </strong>and<strong>
    <%= + like.user.name %></strong> like this
  <% elsif index > 1 %>
    </strong><%= "and" +(likes.size-index).to_s + " others" %> like this
    <% break %>
  <% elsif index==likes.size-2 || index == 1 %>
    <%= like.user.name %>
  <% else %>
    <%= like.user.name + ", " %>
  <% end %>
<% end %>

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
  <% if post.photos.size == 1 %>
    <%= image_tag post.photos.first.image.url(:standard), class: "card-img-top" %>
  <% else %>
    <div class="carousel slide" data-ride="carousel" id="carousel-post-<%= @post.id %>">
      <div class="carousel-inner">
        <% post.photos.each do |photo| %>
          <% if photo == post.photos.first %>
            <div class="carousel-item active">
          <% else %>
            <div class="carousel-item">
          <% end %>
              <%= image_tag photo.image.url(:standard), class: "card-img-top" %>
            </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  <% end %>
<% end %>

app/views/posts/_posts_list.html.erb
<% @posts.each do |post| %>
  <div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
      <%= link_to user_path(post.user), class: "no-text-decoration" do %>
        <%= image_tag avatar_url(post.user), class: "post-author-icon" %>
      <% end %>
      <%= link_to user_path(post.user), class: "normal-color no-text-decoration",
        title: post.user.name do %>
        <strong><%= post.user.name %></strong>
      <% end %>
      <% if post.is_belongs_to? current_user %>
        <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
          <i class="far fa-trash-alt" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>

    <%= render "photos", {post: post} %>

    <div class="card-body">
      <div class="row actions">
        <div id="like-icon-post-<%= post.id.to_s %>">
          <%= render "like_icon", {is_liked: post.is_liked(current_user), post: post} %>
        </div>
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        <div id="bookmark-icon-post-<%= post.id.to_s %>" class="ml-auto">
          <%= render "bookmark_icon", {is_bookmarked: post.is_bookmarked(current_user), post: post} %>
        </div>
      </div>
      <div id="like-text-post-<%= post.id.to_s %>">
        <%= render "like_text", {likes: post.likes} %>
      </div>
      <div>
        <span><strong><%= post.user.name %></strong></span>
        <span><%= post.content %></span>
      </div>
      <!-- load comments -->
      <div id="comment-post-<%= post.id.to_s %>">
        <%= render 'comment_list', {post: post} %>
      </div>
      <%= link_to time_ago_in_words(post.created_at).upcase + " AGO", post_path(post),
        class: "light-color post-time no-text-decoration" %>
      <hr>
      <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
        <%= render 'comment_form', {post: post} %>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        Create Post
      </div>
      <div class="card-body">
        <%= form_for @post, :html => {:multipart => true, :class => "dropzone upload-images p-0 border-0"} do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-author-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :content, class: "form-control border-0",
                placeholder: "Say something about this ..." %>
            </div>
          </div>
          <div class="fallback">
            <%= file_field_tag "images[]", type: :file, multiple: true %>
          </div>
          <div class="dz-message m-0"></div>
          <div class="dropzone-previews mb-3">
            <div class="upload-photos-icon">
              <i class="fa fa-plus fa-2x" aria-hidden="true" style="color:#dddfe2"></i>
            </div>
          </div>
          <%= f.submit "Post", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div id="posts">
      <%= render 'posts_list' %>
    </div>
  </div>
  <br>
  <%= will_paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row post box col-xl-10 col-lg-11 col-xs-12">
    <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
      <div class="align-self-center">
        <%= render "photos", {post: @post} %>
      </div>
    </div>
    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
      <div class="row px-3 d-flex align-items-center">
        <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
          <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
        <% end %>
        <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
          title: @post.user.name do %>
          <strong><%= @post.user.name %></strong>
        <% end %>
        <% if @post.is_belongs_to? current_user %>
          <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %>
            <i class="far fa-trash-alt" aria-hidden="true"></i>
          <% end %>
        <% end %>
      </div>
      <hr class="mb-0">
      <div class="comment-list py-2">
      <% if @post.content.present? %>
        <div>
          <span><strong><%= @post.user.name %></strong></span>
          <span><%= @post.content %></span>
        </div>
      <% end %>
        <!-- load comment -->
        <div id="comment-post-<%= @post.id.to_s %>">
          <%= render 'comment_list', post: @post %>
        </div>
      </div>
      <hr class="mt-0">

      <div class="row actions">
        <div id="like-icon-post-<%= @post.id.to_s %>">
          <%= render "like_icon", {is_liked: @is_liked, post: @post} %>
        </div>
        <a href="#" class="core-sprite comment hide-text">Comment</a>
        <div id="bookmark-icon-post-<%= @post.id.to_s %>" class="ml-auto">
          <%= render "bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>
        </div>
      </div>
      <div id="like-text-post-<%= @post.id.to_s %>">
        <%= render "like_text", {likes: @likes} %>
      </div>
      <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase %> AGO</div>
      <hr>
      <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
        <%= render 'comment_form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_devisemes.html.erb
<% if resource.errors.any? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mx-auto">
        <a href="" class="nav-item nav-link" href="#">ABOUT US</a>
        <a href="" class="nav-item nav-link" href="#">SUPPORT</a>
        <a href="" class="nav-item nav-link" href="#">BLOG</a>
        <a href="" class="nav-item nav-link" href="#">PRESS</a>
        <a href="" class="nav-item nav-link" href="#">API</a>
        <a href="" class="nav-item nav-link" href="#">JOB</a>
        <a href="" class="nav-item nav-link" href="#">PRIVACY</a>
        <a href="" class="nav-item nav-link" href="#">TERMS</a>
        <a href="" class="nav-item nav-link" href="#">DIRECTORY</a>
        <a href="" class="nav-item nav-link" href="#">LANGUAGE</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "Icon", root_path, class: "navbar-brand core-sprite hide-text" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search",
        remote: true do %>
        <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 text-center common-btn",
          placeholder: "Search", autocomplete: "off" %>
        <div id="users-result"></div>
      <% end %>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <a class="nav-link core-sprite explore-icon hide-text" href="#">Explore</a>
        </li>
        <li class="nav-item">
          <a class="nav-link core-sprite notification-icon hide-text" href="#">Notification</a>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link core-sprite profile-icon hide-text" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_post.html.erb
<% posts.each do |post| %>
  <div class="col-4">
    <%= link_to post_path(post) do %>
      <div class="post-stat d-flex justify-content-center align-items-center">
        <span>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <%= post.likes.size %>
          <i class="ml-3 fa fa-comment" aria-hidden="true"></i>
          <%= post.comments.size %>
        </span>
      </div>
      <%= image_tag post.photos.first.image.url(:standard), class: "card-img-top image-preview" %>
    <% end %>
  </div>
<% end %>

app/views/users/_users_result.html.erb
<% if users.present? %>
  <% users.each do |user| %>
    <%= link_to user_path(user), class: "no-text-decoration normal-color" do %>
      <div class="search-result-item"><%= user.name %></div>
    <% end %>
  <% end %>
<% else %>
  <div class="p-3">
    No results found.
  </div>
<% end %>

app/views/users/index.js.erb
$("#users-result").html('<%= j render "users_result", {users: @users} %>')

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center">
    <%= image_tag avatar_url(@user), width: '152', height: '152', class: "round-img" %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.name %></p>
      <% if @user == current_user %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"></button>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <a href="#" class="list-group-item list-group-item-action">Change Password</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete,
                class: "list-group-item list-group-item-action" %>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="email"><%= @user.email %></p>
    </div>
  </div>

  <div class="profile-tab">
    <% if @user == current_user %>
    <nav>
      <div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-posts-tab" data-toggle="tab" href="#nav-posts" role="tab" aria-controls="nav-posts" aria-selected="true">POSTS</a>
        <a class="nav-item nav-link" id="nav-saved-tab" data-toggle="tab" href="#nav-saved" role="tab" aria-controls="nav-saved" aria-selected="false">SAVED</a>
      </div>
    </nav>
    <% end %>
    <div class="tab-content pb-3" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab">
        <div class="row">
          <%= render "post", {posts: @posts} %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
        <div class="row">
          <%= render "post", {posts: @saved} if @user == current_user %>
        </div>
      </div>
    </div>
  </div>
</div>